/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import proyecto1.cobertura.ListaArray.*;

/**
 *
 * @author sebas
 */
public class VisualizarGrafo extends JFrame {

    private ListaArray listaGrafos;
    private JComboBox<String> selectorGrafos;

    public VisualizarGrafo() {
        // Configuración de la ventana principal
        setTitle("Visualizador de Grafos");
        setSize(600, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Inicializar la lista de grafos usando tu estructura personalizada
//        EJEMPLO DE ESTRUCTURA PARA GUIARME
        listaGrafos = new ListaArray(10); 

        
        Graph grafo1 = crearGrafoEjemplo("Línea 1", "Estacion A", "Estacion B", "Estacion C");
        Graph grafo2 = crearGrafoEjemplo("Línea 2", "Estacion X", "Estacion Y", "Estacion Z");

        // Insertar los grafos en la lista personalizada
        listaGrafos.insertFinal(grafo1);
        listaGrafos.insertFinal(grafo2);

        // Crear los componentes de la interfaz
        JPanel panelSeleccion = new JPanel();
        selectorGrafos = new JComboBox<>();
        selectorGrafos.addItem("Línea 1");
        selectorGrafos.addItem("Línea 2");

        JButton botonMostrar = new JButton("Mostrar Grafo");

        // Agregar el selector y el botón al panel de selección
        panelSeleccion.add(selectorGrafos);
        panelSeleccion.add(botonMostrar);

        // Añadir un escuchador al botón
        botonMostrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mostrarGrafoSeleccionado();
            }
        });

        // Configurar el layout y añadir el panel de selección
        setLayout(new BorderLayout());
        add(panelSeleccion, BorderLayout.NORTH);

        // Mostrar la ventana
        setVisible(true);
    }

    // Método para crear un grafo de ejemplo con estaciones y líneas
    private Graph crearGrafoEjemplo(String nombre, String... estaciones) {
        Graph graph = new SingleGraph(nombre);

        for (String estacion : estaciones) {
            graph.addNode(estacion);
        }
        for (int i = 0; i < estaciones.length - 1; i++) {
            graph.addEdge(estaciones[i] + "_" + estaciones[i + 1], estaciones[i], estaciones[i + 1]);
        }
        return graph;
    }

    // Método para mostrar el grafo seleccionado
    private void mostrarGrafoSeleccionado() {
        String lineaSeleccionada = (String) selectorGrafos.getSelectedItem();

        if (lineaSeleccionada != null) {
            Graph grafoSeleccionado = null;

            // Buscar el grafo en la lista personalizada
            if (lineaSeleccionada.equals("Línea 1")) {
                grafoSeleccionado = (Graph) listaGrafos.getArray()[0].getElement();
            } else if (lineaSeleccionada.equals("Línea 2")) {
                grafoSeleccionado = (Graph) listaGrafos.getArray()[1].getElement();
            }

            if (grafoSeleccionado != null) {
                grafoSeleccionado.display();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
